[2022-09-13 13:36:14,783] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [queued]>
[2022-09-13 13:36:14,973] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [queued]>
[2022-09-13 13:36:14,981] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:36:14,986] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 13:36:14,989] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:36:15,147] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-11T03:00:00+00:00
[2022-09-13 13:36:15,189] {standard_task_runner.py:51} INFO - Started process 39507 to run task
[2022-09-13 13:36:15,268] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-11T03:00:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpkmxw2ly2']
[2022-09-13 13:36:15,306] {standard_task_runner.py:76} INFO - Job 17: Subtask create_employee_table
[2022-09-13 13:36:16,080] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:36:16,620] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T03:00:00+00:00
[2022-09-13 13:36:16,647] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:36:16,725] {base.py:74} INFO - Using connection to: id: local_postgres. Host: 0.0.0.0, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:36:16,739] {taskinstance.py:1396} ERROR - could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?

[2022-09-13 13:36:16,779] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220911T030000, start_date=20220913T133614, end_date=20220913T133616
[2022-09-13 13:36:17,136] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-13 13:39:08,882] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [queued]>
[2022-09-13 13:39:09,048] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [queued]>
[2022-09-13 13:39:09,053] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:39:09,057] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 13:39:09,061] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:39:09,130] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-11T03:00:00+00:00
[2022-09-13 13:39:09,146] {standard_task_runner.py:51} INFO - Started process 42471 to run task
[2022-09-13 13:39:09,167] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-11T03:00:00+00:00', '--job-id', '45', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp2ki9jcj4']
[2022-09-13 13:39:09,178] {standard_task_runner.py:76} INFO - Job 45: Subtask create_employee_table
[2022-09-13 13:39:09,565] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:39:10,060] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T03:00:00+00:00
[2022-09-13 13:39:10,070] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:39:10,201] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:39:10,247] {taskinstance.py:1396} ERROR - FATAL:  database "airflow" does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "airflow" does not exist

[2022-09-13 13:39:10,272] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220911T030000, start_date=20220913T133908, end_date=20220913T133910
[2022-09-13 13:39:10,612] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-13 14:32:17,865] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [queued]>
[2022-09-13 14:32:17,938] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [queued]>
[2022-09-13 14:32:17,940] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 14:32:17,941] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 14:32:17,948] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 14:32:17,989] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-11T03:00:00+00:00
[2022-09-13 14:32:18,003] {standard_task_runner.py:51} INFO - Started process 27410 to run task
[2022-09-13 14:32:18,034] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-11T03:00:00+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpy6fhe77v']
[2022-09-13 14:32:18,044] {standard_task_runner.py:76} INFO - Job 61: Subtask create_employee_table
[2022-09-13 14:32:18,232] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-11T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 14:32:18,422] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T03:00:00+00:00
[2022-09-13 14:32:18,425] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 14:32:18,494] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: student, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 14:32:18,514] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        , parameters: None
[2022-09-13 14:32:18,519] {taskinstance.py:1396} ERROR - syntax error at or near "("
LINE 7:                 primary key (emp_id)
                                    ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 7:                 primary key (emp_id)
                                    ^

[2022-09-13 14:32:18,529] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220911T030000, start_date=20220913T143217, end_date=20220913T143218
[2022-09-13 14:32:18,652] {local_task_job.py:118} INFO - Task exited with return code 1
