[2022-09-13 13:36:17,622] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [queued]>
[2022-09-13 13:36:17,755] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [queued]>
[2022-09-13 13:36:17,765] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:36:17,767] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 13:36:17,769] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:36:17,852] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-12T03:00:00+00:00
[2022-09-13 13:36:17,882] {standard_task_runner.py:51} INFO - Started process 39529 to run task
[2022-09-13 13:36:17,910] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-12T03:00:00+00:00', '--job-id', '22', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpw3bfsdn2']
[2022-09-13 13:36:17,927] {standard_task_runner.py:76} INFO - Job 22: Subtask create_employee_table
[2022-09-13 13:36:18,288] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:36:19,237] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T03:00:00+00:00
[2022-09-13 13:36:19,255] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:36:19,433] {base.py:74} INFO - Using connection to: id: local_postgres. Host: 0.0.0.0, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:36:19,461] {taskinstance.py:1396} ERROR - could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?

[2022-09-13 13:36:19,534] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220912T030000, start_date=20220913T133617, end_date=20220913T133619
[2022-09-13 13:36:19,974] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-13 13:39:08,808] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [queued]>
[2022-09-13 13:39:08,992] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [queued]>
[2022-09-13 13:39:09,002] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:39:09,006] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 13:39:09,008] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:39:09,107] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-12T03:00:00+00:00
[2022-09-13 13:39:09,124] {standard_task_runner.py:51} INFO - Started process 42469 to run task
[2022-09-13 13:39:09,159] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-12T03:00:00+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpxqwpm3or']
[2022-09-13 13:39:09,165] {standard_task_runner.py:76} INFO - Job 43: Subtask create_employee_table
[2022-09-13 13:39:09,550] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:39:09,864] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T03:00:00+00:00
[2022-09-13 13:39:09,878] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:39:09,998] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:39:10,067] {taskinstance.py:1396} ERROR - FATAL:  database "airflow" does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "airflow" does not exist

[2022-09-13 13:39:10,119] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220912T030000, start_date=20220913T133908, end_date=20220913T133910
[2022-09-13 13:39:10,416] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-13 14:32:18,191] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [queued]>
[2022-09-13 14:32:18,261] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [queued]>
[2022-09-13 14:32:18,262] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 14:32:18,263] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 14:32:18,264] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 14:32:18,301] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-12T03:00:00+00:00
[2022-09-13 14:32:18,309] {standard_task_runner.py:51} INFO - Started process 27413 to run task
[2022-09-13 14:32:18,348] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-12T03:00:00+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpqm2ktnku']
[2022-09-13 14:32:18,357] {standard_task_runner.py:76} INFO - Job 62: Subtask create_employee_table
[2022-09-13 14:32:18,506] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-12T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 14:32:18,622] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T03:00:00+00:00
[2022-09-13 14:32:18,624] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 14:32:18,667] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: student, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 14:32:18,694] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        , parameters: None
[2022-09-13 14:32:18,703] {taskinstance.py:1396} ERROR - syntax error at or near "("
LINE 7:                 primary key (emp_id)
                                    ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 7:                 primary key (emp_id)
                                    ^

[2022-09-13 14:32:18,723] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220912T030000, start_date=20220913T143218, end_date=20220913T143218
[2022-09-13 14:32:18,854] {local_task_job.py:118} INFO - Task exited with return code 1
