[2022-09-13 13:13:12,863] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: first_py_dag.bash_dir 2022-09-13T13:11:45.972026+00:00 [queued]>
[2022-09-13 13:13:12,905] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: first_py_dag.bash_dir 2022-09-13T13:11:45.972026+00:00 [queued]>
[2022-09-13 13:13:12,907] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:13:12,909] {taskinstance.py:1018} INFO - Starting attempt 2 of 3
[2022-09-13 13:13:12,911] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:13:12,945] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): bash_dir> on 2022-09-13T13:11:45.972026+00:00
[2022-09-13 13:13:12,951] {standard_task_runner.py:51} INFO - Started process 4025 to run task
[2022-09-13 13:13:12,961] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'first_py_dag', 'bash_dir', '2022-09-13T13:11:45.972026+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_operator.py', '--cfg-path', '/tmp/tmp_fjztb7r']
[2022-09-13 13:13:12,968] {standard_task_runner.py:76} INFO - Job 6: Subtask bash_dir
[2022-09-13 13:13:13,057] {logging_mixin.py:103} INFO - Running <TaskInstance: first_py_dag.bash_dir 2022-09-13T13:11:45.972026+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:13:13,138] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=first_py_dag
AIRFLOW_CTX_TASK_ID=bash_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-09-13T13:11:45.972026+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-13T13:11:45.972026+00:00
[2022-09-13 13:13:13,141] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-13 13:13:13,146] {bash.py:158} INFO - Running command: cd ~/Documents && ls
[2022-09-13 13:13:13,159] {bash.py:169} INFO - Output:
[2022-09-13 13:13:13,209] {bash.py:173} INFO - bash: line 0: cd: /home/airflow/Documents: No such file or directory
[2022-09-13 13:13:13,213] {bash.py:177} INFO - Command exited with return code 1
[2022-09-13 13:13:13,245] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-09-13 13:13:13,253] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=first_py_dag, task_id=bash_dir, execution_date=20220913T131145, start_date=20220913T131312, end_date=20220913T131313
[2022-09-13 13:13:13,333] {local_task_job.py:118} INFO - Task exited with return code 1
