[2022-09-13 13:37:25,647] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-13T13:36:16.862457+00:00 [queued]>
[2022-09-13 13:37:25,703] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-13T13:36:16.862457+00:00 [queued]>
[2022-09-13 13:37:25,708] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:37:25,711] {taskinstance.py:1018} INFO - Starting attempt 2 of 3
[2022-09-13 13:37:25,713] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:37:25,761] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-13T13:36:16.862457+00:00
[2022-09-13 13:37:25,772] {standard_task_runner.py:51} INFO - Started process 40723 to run task
[2022-09-13 13:37:25,793] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-13T13:36:16.862457+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp7__886sd']
[2022-09-13 13:37:25,807] {standard_task_runner.py:76} INFO - Job 32: Subtask create_employee_table
[2022-09-13 13:37:26,027] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-13T13:36:16.862457+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:37:26,213] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-13T13:36:16.862457+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-13T13:36:16.862457+00:00
[2022-09-13 13:37:26,218] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:37:26,281] {base.py:74} INFO - Using connection to: id: local_postgres. Host: 0.0.0.0, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:37:26,291] {taskinstance.py:1396} ERROR - could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?

[2022-09-13 13:37:26,320] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220913T133616, start_date=20220913T133725, end_date=20220913T133726
[2022-09-13 13:37:26,483] {local_task_job.py:118} INFO - Task exited with return code 1
