[2022-09-13 13:36:14,928] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-13 13:36:15,052] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-13 13:36:15,055] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:36:15,064] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 13:36:15,067] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:36:15,178] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-10T03:00:00+00:00
[2022-09-13 13:36:15,198] {standard_task_runner.py:51} INFO - Started process 39509 to run task
[2022-09-13 13:36:15,234] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-10T03:00:00+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmppeawzjjc']
[2022-09-13 13:36:15,269] {standard_task_runner.py:76} INFO - Job 19: Subtask create_employee_table
[2022-09-13 13:36:15,940] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:36:16,396] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-13 13:36:16,405] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:36:16,670] {base.py:74} INFO - Using connection to: id: local_postgres. Host: 0.0.0.0, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:36:16,733] {taskinstance.py:1396} ERROR - could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?

[2022-09-13 13:36:16,801] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220910T030000, start_date=20220913T133614, end_date=20220913T133616
[2022-09-13 13:36:17,220] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-13 13:39:04,751] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-13 13:39:04,905] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-13 13:39:04,910] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:39:04,912] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 13:39:04,915] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 13:39:05,000] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-10T03:00:00+00:00
[2022-09-13 13:39:05,026] {standard_task_runner.py:51} INFO - Started process 42445 to run task
[2022-09-13 13:39:05,067] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-10T03:00:00+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp9evdggm1']
[2022-09-13 13:39:05,089] {standard_task_runner.py:76} INFO - Job 42: Subtask create_employee_table
[2022-09-13 13:39:05,399] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 13:39:06,159] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-13 13:39:06,163] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 13:39:06,348] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 13:39:06,385] {taskinstance.py:1396} ERROR - FATAL:  database "airflow" does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "airflow" does not exist

[2022-09-13 13:39:06,421] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220910T030000, start_date=20220913T133904, end_date=20220913T133906
[2022-09-13 13:39:06,613] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-13 14:32:17,500] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-13 14:32:17,592] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [queued]>
[2022-09-13 14:32:17,594] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 14:32:17,596] {taskinstance.py:1018} INFO - Starting attempt 1 of 3
[2022-09-13 14:32:17,598] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 14:32:17,645] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): create_employee_table> on 2022-09-10T03:00:00+00:00
[2022-09-13 14:32:17,663] {standard_task_runner.py:51} INFO - Started process 27402 to run task
[2022-09-13 14:32:17,707] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_employee_table', '2022-09-10T03:00:00+00:00', '--job-id', '60', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpjs1_ojki']
[2022-09-13 14:32:17,731] {standard_task_runner.py:76} INFO - Job 60: Subtask create_employee_table
[2022-09-13 14:32:17,884] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.create_employee_table 2022-09-10T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-13 14:32:18,056] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T03:00:00+00:00
[2022-09-13 14:32:18,061] {postgres.py:69} INFO - Executing: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        
[2022-09-13 14:32:18,135] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: student, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-13 14:32:18,159] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee(
                emp_id varchar,
                first_name varchar,
                last_name varchar,
                designation varchar
                primary key (emp_id)
            )
        , parameters: None
[2022-09-13 14:32:18,165] {taskinstance.py:1396} ERROR - syntax error at or near "("
LINE 7:                 primary key (emp_id)
                                    ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 7:                 primary key (emp_id)
                                    ^

[2022-09-13 14:32:18,175] {taskinstance.py:1440} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=create_employee_table, execution_date=20220910T030000, start_date=20220913T143217, end_date=20220913T143218
[2022-09-13 14:32:18,270] {local_task_job.py:118} INFO - Task exited with return code 1
