[2022-09-17 03:02:12,677] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.insert_records 2022-09-16T03:00:00+00:00 [queued]>
[2022-09-17 03:02:12,718] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: postgres_dag.insert_records 2022-09-16T03:00:00+00:00 [queued]>
[2022-09-17 03:02:12,719] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 03:02:12,720] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-17 03:02:12,721] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 03:02:12,747] {taskinstance.py:1038} INFO - Executing <Task(PostgresOperator): insert_records> on 2022-09-16T03:00:00+00:00
[2022-09-17 03:02:12,752] {standard_task_runner.py:51} INFO - Started process 49557 to run task
[2022-09-17 03:02:12,761] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'insert_records', '2022-09-16T03:00:00+00:00', '--job-id', '228', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp5xmas0x9']
[2022-09-17 03:02:12,771] {standard_task_runner.py:76} INFO - Job 228: Subtask insert_records
[2022-09-17 03:02:12,888] {logging_mixin.py:103} INFO - Running <TaskInstance: postgres_dag.insert_records 2022-09-16T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-17 03:02:13,061] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=insert_records
AIRFLOW_CTX_EXECUTION_DATE=2022-09-16T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-16T03:00:00+00:00
[2022-09-17 03:02:13,064] {postgres.py:69} INFO - Executing: 
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l101','Bayo','Lanre','Software-developer');
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l1201','Diaz','Mora','Data Scientist');
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l4101','Chris','Muff','scrum-master');
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l1301','Inder','Ajith','Manager');
        
[2022-09-17 03:02:13,100] {base.py:74} INFO - Using connection to: id: local_postgres. Host: host.docker.internal, Port: 5432, Schema: student, Login: postgres, Password: XXXXXXXX, extra: None
[2022-09-17 03:02:13,126] {dbapi.py:180} INFO - Running statement: 
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l101','Bayo','Lanre','Software-developer');
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l1201','Diaz','Mora','Data Scientist');
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l4101','Chris','Muff','scrum-master');
            INSERT INTO employee (emp_id,first_name,last_name,designation)
            VALUES ('l1301','Inder','Ajith','Manager');
        , parameters: None
[2022-09-17 03:02:13,135] {taskinstance.py:1396} ERROR - duplicate key value violates unique constraint "employee_pkey"
DETAIL:  Key (emp_id)=(l101) already exists.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "employee_pkey"
DETAIL:  Key (emp_id)=(l101) already exists.

[2022-09-17 03:02:13,155] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=postgres_dag, task_id=insert_records, execution_date=20220916T030000, start_date=20220917T030212, end_date=20220917T030213
[2022-09-17 03:02:13,253] {local_task_job.py:118} INFO - Task exited with return code 1
